spring:
  application:
    name: oauth2server

server:
  port: ${PORT:8082}

app:
  issuer: ${OAUTH2_ISSUER:http://localhost:8082}
  client:
    verifyUser:
      url: ${VERIFY_USER_URL:http://localhost:8081/auth/verify}